---
type: showroom
tabs:
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
    external: true
  - name: Terraform Enterprise (TFE)
    url: https://tfe-https-${guid}.${domain}/session
    external: true
  - name: HashiCorp Vault
    url: https://vault-${guid}.${domain}/ui/vault/unseal
    external: true
  - name: VS Code
    url: https://vscode-${guid}.${domain}
    external: false
  - name: "TERMINAL"
    url: /wetty_vscode
  - name: Cloud (AWS)
    url: /cloud
