username: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          35363864623263356466333961373831313039636536316165326165626631333264363735623131
          3331396233386561646530353631333031623362653866380a383238323536343537313262303431
          61653765373931336138636636643630366265333764376330303264626438316134633466383432
          3964303264656466380a306437336239366562643038653131393462663132386162353435353962
          36383838646637313036643465633337326562623137623366393638653062303264
password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          61373461383165656566343365306335323639313865643335613235346665646338363666313338
          6332353961336535303561363266303539313833643861300a613539336139313937303937633965
          31303831323237336533643032343432346663666538653863383937653865343339363566653630
          6665663834326237360a643634626233643233623962393239343064386538633439666530396261
          30376563313638353139663237383733656133353362643864306565386566333061323861636431
          63303338643131356164353262323537396364373939343831666463656664623733623863303238
          61663561626263353436313863373630336433613835303534393832336536303635626430336336
          38396233666639613861
reg_username: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          62636562356533383331313332373633303632653137323534366439333530633666353736313832
          6664613236663031353065313530663962336665663062630a343535613531326532313236303033
          39383565613135643439383433373066393038623930623431396437646564306637373237373633
          3366623635363232660a613336623864646566363139383463306137306138306638613462653936
          6363
reg_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          35366637623834393135353039393231333963346130316463623035613931376361326262356363
          6138336433626632376562376437333861313430303534350a333461613865656235343134313831
          63313233656531356135656536316165366635333932323534313634633339343362333663336334
          6232366166353865340a313538313634323862656337396639623732633135313361326565376438
          31666164333966396536643839653632316536613865626136373832623533323562

ssh_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          33303766663736336434333132633066323339336137386531313834333863633965386533363932
          3432333663333332373531376231633636373063646436640a633933333739336232623031633062
          34306134613961623634623133396135613133346139316366616439383130616138646662303061
          3434393938346165360a653732363834663134383237363236313533636330666536363361326431
          32626534366530386163666231346238316431653235343366313632623336323938376662373338
          64323439353234623761633939376232396164373266633334366533636636366638306262616230
          30376438656537306262356464623733643437646537386163373136323366336636376461336431
          38323465326263303533646234366239653739326161356434646465386337313230373166313432
          35393334343132366538643963346632306335336465633835326331383239666637363738653165
          66663435336333333831373531636634343965383263326464336164333338316266653963333433
          64623365326234313831396261626235636461383462373665353331333866346437333138396433
          38336364383731323130376466616463616231353030633636356365633738363466336134666339
          66323935343332333236313765643734373137363738373239656535316334313532363165613366
          31633639313333653562363066313663303265313235626530393130353963626338653433636431
          33663634626433366537323735343464383765636232383239393962653839656535343061643137
          63386137653863636431343437646164646664353566396637363162386237326665636638646432
          61343063353266336537623035363830373535383766636662303265313935666236343039656331
          64646537303564356333346232613236326266333861373530326331376430336538323232613366
          31373836643737396237336533636463326636316335653132363663373136643461663333303030
          31343732303535386265653965393035343464376230653337353033356165336135346133363230
          36636435356434363739323633356464333663616638613263326332656638343933653236633661
          35343362623435323532326530383265323135646335663236613235353535313033653930343733
          64313036353137383866316664376432366633656434623562316132356166613334353835306362
          64303265623138393061303338376533393236636263346236666338636563393239623566313534
          3437

vaultlic: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          61323062343733633832363632613037613634363862386362646132396536626465326533313438
          3339663361623439343530616463323261613361396164350a643534633136303139363434326335
          35316462356539643733356464383263393532653038323561396237663730633763393532363262
          3164386663643639320a613063613836306566353738626665343762383264633138336636313230
          64363666623334323361636464663130613139353332313734306437656533653738633863633734
          34343439346131353334646332333563656436613336376463356238363736613464626439616230
          62616638626265643130373634323738656237383364666533363732363766376563386235663562
          61653638646438306431383131613437393165326138356165623237653930646337353939343834
          63616139316261323261393336313530363233366163343466333638353233633536656663336131
          35393865393662363835363531323666323039666531326435326633373866366464393432633533
          33376135386236326638393036326430663439313061363833303036663137646539333463356135
          65356364623430353964363039393930366431323335646665343564306430323839323063373137
          62393961666365616538653033383839333138366661363561376533303461373139653063346264
          32663033656330326163623139393938383863636430313464303636303532623330336430623131
          65393830623532663639666633623737653661373466383239646139623135373437613132613238
          32363834663162353534303534336630343762373730313664393430633539353331616634323836
          62626330386162323036633532336539656232633030663563343037613730373136326231353736
          37353538366161616136343265363230363132393065323031376136643731323936343162323037
          33323263333264633865343264353631306466623631356265656434383762643332383666373964
          36323434306563396234613233386237626537656461626233393730356639616566366333346331
          65306432333335333838373032316432306461333166356366386330383963623533623231626366
          65363236373962633165646563356237363230303533373163363231363938376535366361333838
          36383936663532326131373534613966626163386661386130643330653961396265613064656332
          61376663636366353331373838613462366239633935323033373735313138306663333066653566
          34363362383235323031326161313636623632333633323639353731613532363738636636363361
          64396238356334393266633863353939656537663365663133666264353137353832656539313932
          35333232303130336234386164353532303137633831333961613037306633376231393764366665
          31386532666238626631383764323836613830336135333437623666316139356332363438323666
          36393634666635613232653034336230613332653535346336363032623538306139313734383563
          63363166643135623638336135366437653262646466313734333333306537326439613665386530
          62373335643234663264396537313163396436643366393337653565343264363130383237396264
          38666239386165653131386132636461303935363564376134363764626437636237346564336138
          39613534653535353463383166396663353636313739633264333531623666356630373433383234
          62373636386264336635393564366133343836663536316139373965386266333036363232336530
          65613038396133383137636532376530373031343034363132353937373632653539626230396330
          63666537346230636361613664623833363663323239626433623732383531663732653764383534
          37646537386437633330383133633964646535333037326239656366396438313930383837393434
          64353536353861626534636164323763643136306564363032633630386466336438386437373765
          62636465333765646261343236323936613130333934633662633965383764386538613037376530
          38626430363831363632663438613936316664633066363736363539306335643033393139376439
          31386539353337323736313235643633373831356430376330303539653538353835313262313763
          61326338346266653232633335656632363861386162656635623164346362393231663935626232
          63393361643233313831303233343637323363383231343134363732663863373935666339613337
          33633862353632393763346236383238376633633530343539303232363061316336613363383533
          38636430643265316162396131653531663563373034373361313833623732353234663462643538
          31623631653731356630353661666633323065386539663239333137376163306464663266636262
          36346334313133613366373139663662373238306430323734396135366537623765613030633834
          34633530663037376638663465666134626131623561393962663863393665323831393532316566
          38666433663237383130313936306565623935316538356538663539663733353665366161616365
          39336161393736373531653530353663646436343631646338613937653466323838636332656137
          31356664313539653430646265393865316437613832393831353435666462653938663834343463
          39366638376330376564366262313534636630643764633935346233336637353761633364346364
          30356566303336306463383234323138353636316637353266356435663065316437393137653566
          64356566336238653939326539303562303562376535373738323436326266623935633538326330
          37666237633662366161363262333064383838373631353734616264633666333363633762333636
          61386463393432633438353637393230663033303061616637616166313364633361666434666435
          65386432393535396434346163313232303364363663613765666330323766393265323733333034
          34393166356336626139653962626232363430333335656463316662363664333430636666636237
          62626664643862376239616266643765376666636462323734323330656433373564633862383865
          30646432303036306132663232326634653132353965326234666134373633303836353435383835
          39373434636333303739386661346230633465326539343030356563633034313632363437653736
          38343331643035623231636438663337653936623938393966653234663935346664666231353331
          65613638333465303161663730373038393536346135316637326333343436613466373534353565
          65393834366430643633623061656238646233333738326337383037363930396537636166626238
          36643363316465353661393633326238363262326338333031373661393137356438363962623962
          36666639346136633165346666323130663462323562373833663230336434613263383333396231
          34666165616362323465366236616530616234326536306463316363356237316636643461656263
          64663439653262343235393961646439613535383934636331616535383665366636363436633035
          31616131343431376261323065346434623962656538353363303132616437636431663535303139
          65366331336337313563343932356337323838656165623864353666343230356461343838656332
          62613835636339623866633962373064386637363433346162623632326139363731616536643732
          63316363303631616239616232363465643764383035393335336631633830313535326261376230
          3239

tfelic: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          62613531343563636332316561373037336233636438333838353866323134316630653665633839
          3564303931386563306466663230663233633064653234370a386431643665306165653039353962
          62363135363262633865623964303662373862623939306164646630666534323331623036353239
          3465363331643939630a356236393864303434636631306264343136383930623564386632636333
          66653735346438313861636164646162346231376165663161336263303233306635623236313165
          66623734636337393165376564373966303665613235666465376534653966316365643062333232
          39366231393966373835653966346463396363643362376639623965643531363231653165633963
          66623837613737623762336237306435646431316233333637336634623935666130343137376430
          33326537666362313431626437303865333633326461333434633339346165636333326566356366
          62623137396338623934653638343033646265383834646237613433653537396466373766346139
          34636238643333356261353632373631373631396263333065313831613436616333313738343461
          31643932366139616561376661313137376534613864363535316538393565646361613430323762
          34303835383436613730353930663236623235656539653938383630363535353338346535643165
          34376566356330663532613461343331653561373233623066366563373165613539343438616566
          32303761316663613162366332326533363339626530376537646637346665646266613163393363
          64333832356539333761663462343666623265666437326331373463653263656462336634666136
          39363634393636363162393038356634363562386164316661373765316534363366333065373238
          33616431316563616362386630336237643761653835333136346433633837613738353533316531
          36333834393039626364633835393931616663636563636166373762626131343837373265663661
          34623965376238383932656161353532313666626566343666333137373063393064363062626431
          64373932643734666533386432623732323538336334626233616164353237373332316162396363
          30393461646364343066613236643031333439333533316633663030306236646334393131623435
          37376163356466373262343332323663376166323334303463386137323036393535323034653565
          61386238323664646136343031656561346238346365336230643064343234323034313461623134
          30363963666664373866346430303634373934386239646233366165643833646130353031303466
          32396433303634343564333332373664636430616635333936663364396163393036623161613563
          65373266633764396134363162393030393136623134306239393236643835633266653130333663
          34336239363863663832333233383138366663326231643663636230303462633931613235653233
          39316333613863636634656332346138313765613761616436333133313965613861616230386231
          35333733666137363865653563323737353138373262616661303336363731633064343230383261
          33646337333335393835316565373265663632653866653465323230633134653430313132333638
          36336530356562656665333561363431346534363862636461663463646335663964633437353331
          61356536343330313032616437333935353933356266666334666636383365376532386130346630
          63373031633131313065636236346563623631643263313530373962393431313033333639326332
          62383730383563643534313737666334306238303633643161326133393861393330643965373766
          35653037633366663939313835353464383636303434313433636131656538656436313436336236
          32396566376331353831653030366162386630656665643035376233646633386632383666376264
          61386333373165656139386465373165323738323266303433626162643239643564616162633030
          35346566396232313634366365626635336232343233386563313263643263623631356634363066
          31643861643733313665303864633766306638323666623731356338326666626563376535626437
          33656538376233313233383436646335636265393564353032646135376265343165353462366163
          30366461363134316532613338353336663135376237353263656438646563373034343836623939
          66306339323436373264653065363536333430356538366233386433323231653035303731353437
          32613661356339643164623035616534313733623964373861393966653164343636333261633733
          39323465656535636165643233666235326461613633393633306331306535356363313930323936
          35366232373635613231343166363633616563333865336635383461323064616530303833653865
          61643337653866306335653438333165333633316263366633386238306431353535313662373430
          66316164326363306632303935633436386462633361376162623038616336316265653030303832
          39656132346266666336393630313136323637643934613939646566373964613961363939613036
          33623035333137386435306664633833643861353438633664313330376363336465623364326661
          65303664376235316637373462323233633039323339396539353561623235376165613831653337
          65653833343831316633653961623431626636636532383766386332616135336663343533303461
          37383938653765326463653963643430643338363437343238306266656662303639393332636433
          62643465366462653133643232643330636434326536356136346463633864313132343238656233
          32386365336336633139666265313965373135373330326439333338636363383230666335383462
          65656162623132636661666662613230643566333236646130326630383939636366313666356332
          3439
