username: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          35363864623263356466333961373831313039636536316165326165626631333264363735623131
          3331396233386561646530353631333031623362653866380a383238323536343537313262303431
          61653765373931336138636636643630366265333764376330303264626438316134633466383432
          3964303264656466380a306437336239366562643038653131393462663132386162353435353962
          36383838646637313036643465633337326562623137623366393638653062303264
password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          61373461383165656566343365306335323639313865643335613235346665646338363666313338
          6332353961336535303561363266303539313833643861300a613539336139313937303937633965
          31303831323237336533643032343432346663666538653863383937653865343339363566653630
          6665663834326237360a643634626233643233623962393239343064386538633439666530396261
          30376563313638353139663237383733656133353362643864306565386566333061323861636431
          63303338643131356164353262323537396364373939343831666463656664623733623863303238
          61663561626263353436313863373630336433613835303534393832336536303635626430336336
          38396233666639613861
reg_username: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          62636562356533383331313332373633303632653137323534366439333530633666353736313832
          6664613236663031353065313530663962336665663062630a343535613531326532313236303033
          39383565613135643439383433373066393038623930623431396437646564306637373237373633
          3366623635363232660a613336623864646566363139383463306137306138306638613462653936
          6363
reg_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          35366637623834393135353039393231333963346130316463623035613931376361326262356363
          6138336433626632376562376437333861313430303534350a333461613865656235343134313831
          63313233656531356135656536316165366635333932323534313634633339343362333663336334
          6232366166353865340a313538313634323862656337396639623732633135313361326565376438
          31666164333966396536643839653632316536613865626136373832623533323562

ssh_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ansiblebu_vault
          32313437646566386133353332366161633166656630653866346139646632356437343931343430
          6231396430373763363134343864623633656236383735370a643636346531323230373035313565
          63396631333332346566326438306339613062366635616565376134353032373237363334316332
          3931343239303662350a633762353730366630346564643337353661666363376535343261613036
          62626436353863313662306664343739376364393933336562333035393737613862386664323632
          35643165333137663334613432383134366634383139363463323338623561363239373233363037
          30303763386563393733366262343833623132656534653761366136346237353261353031616538
          31653331373461643164376165343761316534663537346539633562643339643939376431633733
          37343564613130393464653838633733383237393631663234383363363261623161363638376431
          35366138383831613839313139346239633538653665623165343635323865316132663032613265
          38663265613833643663353061613531376434363764663164636433333335363833623936343536
          32383332663862643339396161343234353437633534643336616666653037383864313538366364
          37356264633237656138383731666634353330306435373036653432336237623836353134316130
          36323732333366633034376365643931393330646230343636663236323663323034376632346530
          31633465653235323963393665323536323334333330653064313366653635646633343338646636
          37323333323135646164373565643266306238636334396234303233613363323331303866656164
          65303765306564313833323635313733666336363662633565613063666234313235343763396465
          37306431653466653330633663666166303939303938653839656537313537333939386137363030
          61376634373132656165343039646433666538616135343730656437343335353566343138393537
          35326163343264326538393032343339626261653031646361623234306662303565303839323330
          65356236616330633636333938333663623730303832613130373733313066666462663537383639
          36336362633162313137626534643439646632323633373233313464636434626438366564363562
          63633539656335653561313636646634653134303635333432656362303738626430653734636131
          39346336303334393263663133353838633036326338646664306333323137653339656134613136
          3663
